### ISSUE TITLE
Handling ZIP/RAR downloads

### ISSUE THREAD

**Issue by clarkd** [hjhart/seedboxio-docker-downloader#1]
This looks great - thank you!

Does it handle the unpacking/extracting of RAR or ZIP downloads?

**Comment by hjhart** [comment]
I think that would need to be handled inside of deluge somewhere, that way resilio-sync will push it back down as video files, and radarr or sonarr will detect them.

**Comment by hjhart** [comment]
If you come up with a solution, feel free to post it here. If you have more questions feel free to re-open the issue.

**Comment by clarkd** [comment]
I'm a little confused as to your mention of Deluge - aren't you using Rutorrent for this?

**Comment by hjhart** [comment]
Oops, sorry, yeah. Wasn't paying attention. I am using Rutorrent.

**Comment by clarkd** [comment]
No worries. Think I've got it working with Rutorrent, using the AutoTools
and Unpack plugins!

**Comment by clarkd** [comment]
And then notably, ignoring rarely/zip parts with Resilio!

**Comment by hjhart** [comment]
Excellent, good to hear!
