### ISSUE TITLE
Save config

### ISSUE THREAD

**Issue by robahearts** [hjhart/seedboxio-docker-downloader#2]
How do you save the configuration of the containers?

**Comment by hjhart** [comment]
Great question! In the docker-compose.yml file, it mounts volumes from the local directories `jackett/config`, `radarr/config` and `sonarr/config` to the config directories inside the containers.

I'm not 100% positive it is working, but the directories do update when I change jackett configuration. 

I haven't had to make this too portable yet, so it could probably use some more tests. Pull requests are definitely welcome.

**Comment by hjhart** [comment]
Great question! In the docker-compose.yml file, it mounts volumes from the local directories `jackett/config`, `radarr/config` and `sonarr/config` to the config directories inside the containers.

I'm not 100% positive it is working, but the directories do update when I change jackett configuration. 

I haven't had to make this too portable yet, so it could probably use some more tests. Pull requests are definitely welcome.
