### ISSUE TITLE
Setup without docker?

### ISSUE THREAD

**Issue by xpronic** [hjhart/seedboxio-docker-downloader#3]
Sorry if this is too much to ask, but I already have sonarr/radarr/jackett setup locally, but was wondering how I would connect it to Resilio Sync without docker? I'm willing to reinstall if I can somehow save my settings. New to seedboxes, and yours was the best setup I've found.

**Comment by hjhart** [comment]
Refer to the sync image that is installed via the docker-compose.yml file.
Check out that images Dockerfile. Then see how it uses the RSLSYNC_SECRET
environment variable.

**Comment by hjhart** [comment]
Here is the documentation for that docker image:
https://github.com/nimmis/docker-resilio-sync/blob/master/README.md

**Comment by xpronic** [comment]
Thanks. All sorted.
