### ISSUE TITLE
Windows Setup Documentation

### ISSUE THREAD

**Issue by ghost** [hjhart/seedboxio-docker-downloader#4]
### Windows 10 Stack Essentials

[Windows 10](https://www.microsoft.com/en-us/software-download/windows10): Clean, jank-free, fully functional copy of  Windows 10 is of the utmost importance. If you have any jank in there, it might cause problems, as you are touching a lot of layers here - (OS, Hyper-V, Containers, etc.). This didn't work correctly for me until I completely wiped my system, although you shouldn't have to in most cases!

Plex - Lorem Ipsum

Plex Media Server - Loren Ipsum

[Seedbox.io Seedbox](https://seedbox.io/): This won't work without one of these, please [read up on them](https://seedboxgui.de/guides/what-is-a-seedbox/) so you have a full understanding of what these do. It comes with EVERYTHING you need, and it's also the thing in the screenshot when you set your CompletedDirectory folder. More on that later.

How to set Environment Variables on your Windows 10 system: This one is no biggie as long as you RTFD, but very, very important you get it right. These are the meat and potatoes of this stack, and if they aren't set correctly, your in for a real treat. 
 
Make sure you set the following variables in your [Environment Path in Windows 10](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/):

- [ ] SEEDHOST - Put YOUR Seedbox.io URL information in here, minus the [http://] part. It should look something very close to > (psv23232.seedbox.io). Yours will be different, so don't cut and paste and expect miracles!

- [ ] MOVIE_DIR - This value is the File Explorer path to your movies. (Example: M:\Movies)

- [ ] TV_SHOW_DIR - This value is the File Explorer path to your tv shows. (Example: T:\TVShows)

- [ ] STORAGE_DIR - This value is the File Explorer path to your CompletedDownloads folder that Resilio Sync will use

[Resilio Storage Sync](https://www.resilio.com/individuals/): You'll need this to sit between your containers and Plex.

Basic coding skills: As long as you can change directories, and remember where you put your folders, you'll be ok! Oh, and we'll be doing some Powershell and Bash CLI too! Fun stuff!
  
[Docker for Windows](https://docs.docker.com/docker-for-windows/install/): This is where all the magic happens. It puts all the cool things in one nifty container. More on Docker [here](https://en.wikipedia.org/wiki/Docker_(software)).

[Powershell CLI](https://docs.microsoft.com/en-us/powershell/scripting/components/console/powershell.exe-command-line-help?view=powershell-6): This ships with Windows, but I included a link to the documentation in case you're just starting out!

[Git](https://git-scm.com/download/win): You'll need this for the bash terminal to export your environment SEEDHOST variable. Once this is installed on your system if you install Visual Studio Code, [you can create a bash terminal inside of the IDE itself](https://stackoverflow.com/questions/42606837/how-do-i-use-bash-on-windows-from-the-visual-studio-code-integrated-terminal), very cool!

### Windows 10 Stack Nice-To-Haves

[Visual Studio Code](https://code.visualstudio.com/): You don't need this per se, but you can select multiple terminals right from one place, making this a whole lot easier! It also integrates with Docker!

 **Click on the links below to learn more about:**

[Switching Terminals](https://code.visualstudio.com/docs/editor/integrated-terminal)

[Official Visual Studio Code Docker Extension](https://code.visualstudio.com/docs/editor/integrated-terminal)

[Visual Studio Marketplace Docker Extensions](https://marketplace.visualstudio.com/search?term=docker&target=VSCode&category=All%20categories&sortBy=Relevance)

**Comment by hjhart** [comment]
I'm happy to accept pull requests if you've got this working on Windows. I'm not sure what the issue is here.
