### ISSUE TITLE
Folders Created in Download location (NTFS 8TB Drive) yet no files download

### ISSUE THREAD

**Issue by stakeout55** [hjhart/seedboxio-docker-downloader#5]
Good afternoon! Firstly, this script is amazing and I really appreciate you taking the time to make it! I am hitting a small wall: I'm on CrunchBang++ (Debian 10) - and everything *appears* to be set-up properly, yet on my 8TB drive NTFS (different than my install disk which is a SSD) - I see folders and paths have been created for syncing from Sonarr yet nothing ever downloads to them. It'll create tv series and episode folders but nothing populates them. Thoughts? Thanks!

**Comment by hjhart** [comment]
Hm, I'm still using this but the context has been all but lost to me. 

I think the way it works is that you set up deluge to automatically move files to those folders, which rsync then picks up.

Did you follow the instructions to move files after completing the download in deluge?

**Comment by hjhart** [comment]
Yeah so, in the README it talks about this:

>Click on the settings icon. Go to "Autotools". Make sure AutoMove is checked, if torrent's label matches filter /.*/ with the directory, /home/psv23232/files/CompletedDownloads. Also check the "Add torrent's label to path" 

Did you enable AutoMove and also "Add torrent's label to path"?

I think the label will be Sonarr or Radarr so it'll plop things into `/home/psv23232/files/CompletedDownloads/Sonarr` and ` /home/psv23232/files/CompletedDownloads/Radarr`, and I think rsync will sync everything in `CompletedDownloads`

**Comment by stakeout55** [comment]
Hey! I appreciate the reply very much, I re-checked all of the labels and such, everything is set-up as it is supposed to be. (Radarr appears to be working fine in terms of downloads). One thing i found was under Sonarr, there is a Category box and under it was sonarr-tv  -- I changed it to sonarr; not even sure if this matters. Now all downloads with both Sonarr and Radarr appear to be working!!! Thank you.      

 I did not see the things on Deluge anywhere!! Is deluge what is responsible for moving the downloaded content to the respective folders that I placed in the .env ?   Would you mind supplying a link pretty please? I very much appreciate your time!

**Comment by hjhart** [comment]
Oops, I think I mixed up deluge and rTorrent. I meant rTorrent! It's what downloads the torrents. 

Glad it worked out for you! Closing ticket as it feels resolved.
