### ISSUE TITLE
what happens to the local synced files after the import

### ISSUE THREAD

**Issue by rj-d2** [hjhart/seedboxio-docker-downloader#6]
hi there, your project looks really interesting, i have one question to the workflow,

rutorrent is finished with the download,
resilio syncs the media to the local drive,
the ..arrs are importing,

how is the media imported, hard link or copy?
how are the left over files handled, because the arrs only copy not move?

tl,dr
what happens to the local synced files after the import?

would be great if you could clarify that for me

**Comment by hjhart** [comment]
After files are synced locally, sonarr / radarr picks it up as completed. I have plex monitoring those directories and it imports them. That’s about it.
